version: "3"

services:
  click-n-wash-db:
    image: postgres
    container_name: click-n-wash-db
    restart: on-failure
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_DB: ${DB_NAME:-cnw-db}
      POSTGRES_USER: ${DB_USER:-cnw-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-cnw-password}
    volumes:
      - click-n-wash-db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  click-n-wash-db-data:
    driver: local

networks:
  default:
    name: click-n-wash-network
    driver: bridge
