version: "3"

services:
  click-n-wash-db:
    image: postgres
    container_name: click-n-wash-db
    restart: on-failure
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_DB: ${DB_NAME:-cnw-db}
      POSTGRES_USER: ${DB_USER:-cnw-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-cnw-password}
    volumes:
      - click-n-wash-db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    container_name: click-n-wash-app
    build: .
    ports:
      - ${PORT:-8080}:${PORT:-8080}
    env_file:
      - .env
    environment:
      DB_HOST: click-n-wash-db
      VITE_FRONTEND_ADDRESS: http://localhost:${PORT:-8080}
    depends_on:
      - click-n-wash-db

volumes:
  click-n-wash-db-data:
    driver: local

networks:
  default:
    name: click-n-wash-network
    driver: bridge
